### PR TITLE
SLURM migration

### PR DESCRIPTION
**Pull request by pmb59**

### CODE REVIEW

**Review by anilthanki — APPROVED** [review]
LGTM

**Review by irisdianauy — APPROVED** [review]
LGTM with applicable comments here https://github.com/ebi-gene-expression-group/scxa-droplet-quantification-workflow/pull/25

**Comment by pmb59** [comment]
> [ebi-gene-expression-group/scxa-droplet-quantification-workflow#25](https://github.com/ebi-gene-expression-group/scxa-droplet-quantification-workflow/pull/25)

@irisdianauy  We can't use `partition`, the process directive `queue` is fixed by Nextflow https://www.nextflow.io/docs/latest/executor.html#slurm

**Comment by pmb59** [comment]
Thanks @irisdianauy and @anilthanki for reviewing!

**Pull request merged**
